order:
  - name
  - version
  - description
  - license
  - author
  - homepage
  - bugs
  - keywords
  - main
  - types
  - scripts
  - ...rest
  - dependencies
  - peerDependencies
  - devDependencies
  - optionalDependencies
  - bundledDependencies
